### ISSUE TITLE
1.0.4 doen't get pas loading buildings and road

### ISSUE THREAD

**Issue by aaamoeder** [inferius/MultiBot#2]
`Logging...
Success login
Loaded players data. ID: *******and Name: *******
Loaded other players data. Count: 74
Loaded buildings and road. Count: 253`

that's where it hangs, kept it running for hours, no change.

**Comment by aaamoeder** [comment]
could you please give an update, ? or ways of contacting you for testing ?

**Comment by inferius** [comment]
Hi, 
please download 1.0.4 version again, beacuse i uploaded wrong version before. If the problem appears, contact me.

**Comment by aaamoeder** [comment]
Hey,

First of all thanks for taking your time, I appreciate it !

I tried downloading it again an installing again, but problem stays the
same.

Should I be deleting more then the installation folder when trying to
install a new version ?
also, when I install version 1.0.4 the installed folder says 1.0.3 ?

Would it be possible to remove the .net and flash installs from the package
? i understand you want to deliver a complete package, but once it is
installed it's a hassle to go through every install.

again, thanks for taking your time to contact me and creating this
wonderful piece of software ! ;)

**Comment by inferius** [comment]
Hi,
sorry i'm late, but i have too work.
thats complete package, but still is only self-extract winrar, you can only extract throught winrar :)

Please download new version 1.0.5 and send me  file "last_startup_data.log" created in program dir.

**Comment by aaamoeder** [comment]
downloaded last 1.0.5 and stil gets stuck after loading buildings and roads

**Comment by inferius** [comment]
Hi, 
i fix any bugs, please test new version 1.0.6.

**Comment by aaamoeder** [comment]
I downloaded 1.0.6 and it's working again ! excellent ! :) thank you very much !
