### ISSUE TITLE
Doesnt remember worldname 1.0.6_Beta

### ISSUE THREAD

**Issue by szanka** [inferius/MultiBot#4]
First of all, thank You for a great piece of work!!! :)
Issue:
Bot autmatically logins to first world on the account  in alphabetical order. 
The field World name in config is blank even if it was filled properly before.

Solution that worked for me from time to time:

Manually edit FoE.Config.xml and enter world name

**Comment by aaamoeder** [comment]
seems fixed in 1.0.7 update, check it out ;)

**Comment by szanka** [comment]
yep it works, thx :)
