### ISSUE TITLE
auto pickup and start army production?

### ISSUE THREAD

**Issue by aaamoeder** [inferius/MultiBot#6]
Would it be possible to implement this ? Since i'm now getting to colonial age and it takes ages to train troops, it'd be nice if it could do this :)

txs !

btw, if you ever need help developing/testing the bot.. don't hesitate to ask ;)

**Comment by inferius** [comment]
hi,
i forgot implement this feature because i don't use army but I implement this thing :)

I'll appreciate every help :) This is open source, if you're in the mood you can do anything :)

**Comment by szanka** [comment]
forge points spending would also be a great addition ;)

**Comment by aaamoeder** [comment]
which software applications do you use to develop ?

**Comment by inferius** [comment]
I working on research and trade manager included work with forge points, but i have a little time now :)

Develop in Visual Studio 2017
